In [4]:
import os

print(os.getcwd())

c:\Users\divit\OneDrive\Desktop\business-entity-resolution\notebooks

In [7]:
import pandas as pd

DATA = "../data/train/"

s1 = pd.read_csv(
    DATA + "train_source1.tsv",
    sep="\t"
)

s2 = pd.read_csv(
    DATA + "train_source2.tsv",
    sep="\t"
)

s3 = pd.read_csv(
    DATA + "train_source3.tsv",
    sep="\t"
)

gt = pd.read_csv(
    DATA + "train_ground_truth.tsv",
    sep="\t"
)

print("Source 1:", s1.shape)
print("Source 2:", s2.shape)
print("Source 3:", s3.shape)
print("Ground Truth:", gt.shape)

Source 1: (2206821, 4)
Source 2: (5034616, 4)
Source 3: (5285603, 4)
Ground Truth: (2206821, 2)

In [8]:
print("S1 columns:", s1.columns.tolist())
print("S2 columns:", s2.columns.tolist())
print("S3 columns:", s3.columns.tolist())
print("GT columns:", gt.columns.tolist())

S1 columns: ['entity_id', 'business_name', 'business_address', 'country']
S2 columns: ['entity_id', 'business_name', 'business_address', 'country']
S3 columns: ['entity_id', 'business_name', 'business_address', 'country']
GT columns: ['source1_entity_id', 'matched_entity_ids']

In [9]:
display(s1.head(10))
display(s2.head(10))
display(s3.head(10))
display(gt.head(10))

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [10]:
for name, df in [
    ("Source 1", s1),
    ("Source 2", s2),
    ("Source 3", s3),
    ("Ground Truth", gt)
]:
    print(f"\n{name}")
    print(df.isna().sum())

Source 1
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Source 2
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

Source 3
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

Ground Truth
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

In [11]:
print("S1 duplicate IDs:", s1["entity_id"].duplicated().sum())
print("S2 duplicate IDs:", s2["entity_id"].duplicated().sum())
print("S3 duplicate IDs:", s3["entity_id"].duplicated().sum())

print("GT duplicate S1 IDs:", gt["source1_entity_id"].duplicated().sum())

S1 duplicate IDs: 0
S2 duplicate IDs: 0
S3 duplicate IDs: 0
GT duplicate S1 IDs: 0

In [12]:
for name, df in [
    ("Source 1", s1),
    ("Source 2", s2),
    ("Source 3", s3)
]:
    print(f"\n{name}")
    print(df["country"].value_counts(dropna=False))

Source 1
country
US       1323633
India     883188
Name: count, dtype: int64

Source 2
country
US       3016817
India    2017799
Name: count, dtype: int64

Source 3
country
US       3170056
India    2115547
Name: count, dtype: int64

In [13]:
print(gt.head(20).to_string())

   source1_entity_id                                                                         matched_entity_ids
0          S1-965667                            S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
1        S1-55344266                                        S2-249013014,S2-197070651,S3-478195123,S3-384364074
2       S1-343815751                                                     S2-790675320,S2-479876582,S3-878454467
3       S1-656753428                                                      S2-153058913,S2-24659151,S3-679606215
4       S1-102811957              S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
5        S1-18727616                                        S2-755677256,S3-187831601,S3-641489370,S3-476250621
6       S1-318373630                                                                  S2-660036492,S3-804600254
7        S1-86989137                                                                  S3-274817120,S3-312496301
8        S1-29845983                                                                  S2-648035184,S3-588502663
9       S1-789009573                                                      S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                                                                  S2-356983532,S3-352439310
11        S1-7293388                                          S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636              S2-487600131,S2-582477216,S2-392804085,S3-200008747,S3-729771680,S3-249331830
13      S1-274126313               S2-736616474,S2-680265918,S2-51486805,S3-925631694,S3-461175723,S3-850112871
14      S1-145361722                                                      S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-173295926,S3-858763214,S3-33665521,S3-555791452
16      S1-692000596                                                                  S2-580419223,S3-164220452
17      S1-561341312                                                                  S2-483615364,S3-619529814
18      S1-777597828                                                                  S2-836452886,S3-413669121
19      S1-282467635                                                                  S2-938895481,S3-138350041

In [14]:
gt["has_match"] = gt["matched_entity_ids"].fillna("").str.strip().ne("")

print(gt["has_match"].value_counts())

has_match
True     2083574
False     123247
Name: count, dtype: int64

In [15]:
gt["match_count"] = gt["matched_entity_ids"].fillna("").apply(
    lambda x: 0 if not x else len(x.split(","))
)

print(gt["match_count"].describe())

count    2.206821e+06
mean     3.461253e+00
std      1.705323e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      5.000000e+00
max      1.100000e+01
Name: match_count, dtype: float64

In [16]:
print(
    gt["match_count"]
    .value_counts()
    .sort_index()
    .head(20)
)

match_count
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [18]:
def count_sources(x):
    if not x:
        return 0, 0

    ids = x.split(",")

    s2_count = sum(i.startswith("S2-") for i in ids)
    s3_count = sum(i.startswith("S3-") for i in ids)

    return s2_count, s3_count


gt[["s2_count", "s3_count"]] = gt["matched_entity_ids"].fillna("").apply(
    lambda x: pd.Series(count_sources(x))
)

print(gt[["s2_count", "s3_count"]].describe())

           s2_count      s3_count
count  2.206821e+06  2.206821e+06
mean   1.673728e+00  1.787524e+00
std    1.112813e+00  1.165604e+00
min    0.000000e+00  0.000000e+00
25%    1.000000e+00  1.000000e+00
50%    2.000000e+00  2.000000e+00
75%    2.000000e+00  3.000000e+00
max    5.000000e+00  6.000000e+00

In [19]:
print("S2 matches:", (gt["s2_count"] > 0).sum())
print("S3 matches:", (gt["s3_count"] > 0).sum())
print("Both S2 & S3:", ((gt["s2_count"] > 0) & (gt["s3_count"] > 0)).sum())

S2 matches: 1919076
S3 matches: 1940545
Both S2 & S3: 1776047

In [20]:
positive = gt[gt["match_count"] > 0].head(10)

display(positive)

,source1_entity_id,matched_entity_ids,has_match,match_count,s2_count,s3_count
0,S1-965667,"S2-681193310,S2-743505751,S3-775321672,S3-1129...",True,5,2,3
1,S1-55344266,"S2-249013014,S2-197070651,S3-478195123,S3-3843...",True,4,2,2
2,S1-343815751,"S2-790675320,S2-479876582,S3-878454467",True,3,2,1
3,S1-656753428,"S2-153058913,S2-24659151,S3-679606215",True,3,2,1
4,S1-102811957,"S2-478959098,S2-553508714,S2-625774905,S3-7280...",True,6,3,3
5,S1-18727616,"S2-755677256,S3-187831601,S3-641489370,S3-4762...",True,4,1,3
6,S1-318373630,"S2-660036492,S3-804600254",True,2,1,1
7,S1-86989137,"S3-274817120,S3-312496301",True,2,0,2
8,S1-29845983,"S2-648035184,S3-588502663",True,2,1,1
9,S1-789009573,"S2-383871912,S3-74481402,S3-576451439",True,3,1,2

In [21]:
row = positive.iloc[0]

print("S1:", row["source1_entity_id"])
print("Matches:", row["matched_entity_ids"])

S1: S1-965667
Matches: S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364

In [22]:
s1_id = row["source1_entity_id"]

display(
    s1[s1["entity_id"] == s1_id]
)

,entity_id,business_name,business_address,country
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

In [24]:
matched_ids = row["matched_entity_ids"].split(",")

display(
    s2[s2["entity_id"].isin(matched_ids)]
)

display(
    s3[s3["entity_id"].isin(matched_ids)]
)

            entity_id                 business_name business_address country
1376739  S2-681193310  Maure Wilblims Colombier Inc              NaN      US
2003754  S2-743505751      Maure Williams Colombier              NaN      US

,entity_id,business_name,business_address,country
63830,S3-860443364,Maure Williams Inc Center,NaN,US
1217885,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
5223525,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US

In [25]:
print("S1 ID sample:")
print(s1["entity_id"].head())

print("\nS1 prefix counts:")
print(s1["entity_id"].str[:3].value_counts())

print("\nS2 prefix counts:")
print(s2["entity_id"].str[:3].value_counts())

print("\nS3 prefix counts:")
print(s3["entity_id"].str[:3].value_counts())

S1 ID sample:
0    S1-925783039
1    S1-773889195
2    S1-377745466
3    S1-133037285
4    S1-755362802
Name: entity_id, dtype: object

S1 prefix counts:
entity_id
S1-    2206821
Name: count, dtype: int64

S2 prefix counts:
entity_id
S2-    5034616
Name: count, dtype: int64

S3 prefix counts:
entity_id
S3-    5285603
Name: count, dtype: int64

In [26]:
positive_row = gt[gt["match_count"] > 0].iloc[0]

source1_id = positive_row["source1_entity_id"]
matched_ids = positive_row["matched_entity_ids"].split(",")

print("SOURCE 1 ID:")
print(source1_id)

print("\nMATCHED IDs:")
print(matched_ids)

SOURCE 1 ID:
S1-965667

MATCHED IDs:
['S2-681193310', 'S2-743505751', 'S3-775321672', 'S3-11291185', 'S3-860443364']

In [27]:
source1_record = s1[
    s1["entity_id"] == source1_id
]

display(source1_record)

,entity_id,business_name,business_address,country
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

In [28]:
s2_records = s2[
    s2["entity_id"].isin(matched_ids)
]

s3_records = s3[
    s3["entity_id"].isin(matched_ids)
]

print("S2 matches:")
display(s2_records)

print("S3 matches:")
display(s3_records)

S2 matches:

            entity_id                 business_name business_address country
1376739  S2-681193310  Maure Wilblims Colombier Inc              NaN      US
2003754  S2-743505751      Maure Williams Colombier              NaN      US

S3 matches:

,entity_id,business_name,business_address,country
63830,S3-860443364,Maure Williams Inc Center,NaN,US
1217885,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
5223525,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US

In [29]:
print("S1 prefix counts:")
print(s1["entity_id"].str[:3].value_counts())

positive_row = gt[gt["match_count"] > 0].iloc[0]

source1_id = positive_row["source1_entity_id"]
matched_ids = positive_row["matched_entity_ids"].split(",")

print("\nS1:", source1_id)
print("Matches:", matched_ids)

print("\n--- SOURCE 1 RECORD ---")
display(s1[s1["entity_id"] == source1_id])

print("\n--- SOURCE 2 MATCHES ---")
display(s2[s2["entity_id"].isin(matched_ids)])

print("\n--- SOURCE 3 MATCHES ---")
display(s3[s3["entity_id"].isin(matched_ids)])

S1 prefix counts:
entity_id
S1-    2206821
Name: count, dtype: int64

S1: S1-965667
Matches: ['S2-681193310', 'S2-743505751', 'S3-775321672', 'S3-11291185', 'S3-860443364']

--- SOURCE 1 RECORD ---

,entity_id,business_name,business_address,country
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

--- SOURCE 2 MATCHES ---

            entity_id                 business_name business_address country
1376739  S2-681193310  Maure Wilblims Colombier Inc              NaN      US
2003754  S2-743505751      Maure Williams Colombier              NaN      US

--- SOURCE 3 MATCHES ---

,entity_id,business_name,business_address,country
63830,S3-860443364,Maure Williams Inc Center,NaN,US
1217885,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
5223525,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US

In [32]:
import sys
sys.path.append("../src")

from preprocessing import add_normalized_columns

In [33]:
test_df = train_source1.head(5)

test_df = add_normalized_columns(test_df)

test_df[
    [
        "business_name",
        "name_norm",
        "name_compact",
        "business_address",
        "address_norm"
    ]
]

NameError: name 'train_source1' is not defined

In [34]:
import sys
sys.path.append("../src")

from preprocessing import add_normalized_columns

In [36]:
import sys
import importlib
import pandas as pd

# Add src folder to Python path
if "../src" not in sys.path:
    sys.path.append("../src")

# Import and reload the latest version
import preprocessing
importlib.reload(preprocessing)

from preprocessing import add_normalized_columns


# Load Source 1
s1 = pd.read_csv(
    "../data/train/train_source1.tsv",
    sep="\t"
)

# Test preprocessing on first 10 rows
sample = add_normalized_columns(s1.head(10))


# Display results
sample[
    [
        "business_name",
        "name_norm",
        "name_compact",
        "business_address",
        "address_norm",
        "address_compact",
        "country",
        "country_norm"
    ]
]

,business_name,name_norm,name_compact,business_address,address_norm,address_compact,country,country_norm
0,Orelee's Barbershop,orelee s barbershop,oreleesbarbershop,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,1795westchesterdrivehighpointnc,US,us
1,Prime Money,prime money,primemoney,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,17560ellisroadtahlequahok,US,us
2,B+ Retail Inc,b retail inc,bretailinc,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,1712montebelloavenuephoenixaz,US,us
3,Christ Chapel,christ chapel,christchapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,2100camerondriveunitapartmentgdundalkmd,US,us
4,Prabhav Business Center,prabhav business center,prabhavbusinesscenter,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,797laketownblockakolkatahowrahwestbengal,India,india
5,Custom Wealth Services LLC,custom wealth services llc,customwealthservicesllc,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,ohcolumbus5559orvilleavenue,US,us
6,Consulting Nyasa Nursing Private Limited,consulting nyasa nursing private limited,consultingnyasanursingprivatelimited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,2505tower1oakwoodrunwalgreensmulundgoreagonlin...,India,india
7,Nexus Anchor Rain,nexus anchor rain,nexusanchorrain,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,1111churchstreetunit2007nashvilletn,US,us
8,Moore Bitwise Inc,moore bitwise inc,moorebitwiseinc,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,337oaklandavenuemichigancityin,US,us
9,Dermatology Green Medicine,dermatology green medicine,dermatologygreenmedicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,294meadowcreekdriveunitunit2villageofpewaukeewi,US,us